version: '3.8'

services:
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes

  backend:
    build: ./backend
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=sqlite:///app/antifraud.db
      - REDIS_URL=redis://redis:6379
      - CORS_ORIGINS=http://localhost:5173,http://localhost:3000
    depends_on:
      - redis
    volumes:
      - ./backend:/app
      - backend_data:/app/data

  dashboard:
    build: ./dashboard
    ports:
      - "5173:5173"
    environment:
      - VITE_API_BASE=http://localhost:8000
    depends_on:
      - backend

volumes:
  redis_data:
  backend_data:
